spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    # connection_url/db_name
    url: jdbc:postgresql://localhost:5432/batch14_product_management
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl: none
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  servlet:
    context-path: /product-service
